version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - appnetwork

  backend:
    build: ./backend
    ports:
      - "4000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - appnetwork

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnetwork

volumes:
  postgres-db-volume:

networks:
  appnetwork:
    driver: bridge
